# Generated by Django 3.2.4 on 2022-07-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('event_manager', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('attendees', models.ManyToManyField(blank=True, to='ClubApp.Users')),
            ],
        ),
    ]
