# Generated by Django 3.2.4 on 2022-07-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
