# Generated by Django 3.2.4 on 2022-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_image',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
