# Generated by Django 3.2.4 on 2022-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0003_alter_event_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
