# Generated by Django 3.2.4 on 2022-07-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0005_event_event_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_editor',
            new_name='event_creator',
        ),
    ]
